# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c11929b0bf9c379f976a7286963347c7dd44062ee093dc92902588d4697660b24ac010e113e4e918311edb391a8ba1fc6c1cce4bec540a54d4135fd76cc3a812

test:
  secret_key_base: 527e568b74c7fd73537d252a6c49c376032300b242c404f32cb81c098c071c4d7505cd5cca8107edbe8b5f4e3d779ccea2056f061a2815480a3ea418c58f8f46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
